package merl
import chisel3._
class DecodeReg extends Module
{
	val io= IO(new Bundle{
     val din1   = Input(UInt(1.W))
     val din2   = Input(UInt(1.W))
     val din3   = Input(UInt(1.W))
     val din4   = Input(UInt(1.W))
     val din5   = Input(UInt(3.W))
     val din6   = Input(UInt(2.W))
     val din7   = Input(UInt(1.W))
     val din8   = Input(UInt(32.W))
     val din9   = Input(UInt(32.W))
     val din10  = Input(UInt(32.W))
     val din11  = Input(UInt(32.W))
     val din12  = Input(UInt(32.W))
     val din13  = Input(UInt(5.W))
     val din14  = Input(UInt(3.W))
     val din15  = Input(UInt(7.W))
     val din16  = Input(UInt(5.W))
     val din17  = Input(UInt(5.W))
     val dout1  = Output(UInt(1.W))
     val dout2  = Output(UInt(1.W))
     val dout3  = Output(UInt(1.W))
     val dout4  = Output(UInt(1.W))
     val dout5  = Output(UInt(3.W))
     val dout6  = Output(UInt(2.W))
     val dout7  = Output(UInt(1.W))
     val dout8  = Output(UInt(32.W))
     val dout9  = Output(UInt(32.W))
     val dout10 = Output(UInt(32.W))
     val dout11 = Output(UInt(32.W))
     val dout12 = Output(UInt(32.W))
     val dout13 = Output(UInt(5.W))
     val dout14 = Output(UInt(3.W))
     val dout15 = Output(UInt(7.W))
     val dout16 = Output(UInt(5.W))
     val dout17 = Output(UInt(5.W)) 
})
    val Decreg1 = RegInit(0.U(1.W))
    val Decreg2 = RegInit(0.U(1.W))
    val Decreg3 = RegInit(0.U(1.W))
    val Decreg4 = RegInit(0.U(1.W))
    val Decreg5 = RegInit(0.U(3.W))
    val Decreg6 = RegInit(0.U(2.W))
    val Decreg7 = RegInit(0.U(1.W))
    val Decreg8 = RegInit(0.U(32.W))
    val Decreg9 = RegInit(0.U(32.W))
    val Decreg10 = RegInit(0.U(32.W))
    val Decreg11 = RegInit(0.U(32.W))
    val Decreg12 = RegInit(0.U(32.W))
    val Decreg13 = RegInit(0.U(5.W))
    val Decreg14 = RegInit(0.U(3.W))
    val Decreg15 = RegInit(0.U(7.W))
    val Decreg16 = RegInit(0.U(5.W))
    val Decreg17 = RegInit(0.U(5.W))
    Decreg1:=io.din1
    io.dout1 := Decreg1
    Decreg2:=io.din2
    io.dout2 := Decreg2
    Decreg3 :=io.din3
    io.dout3 := Decreg3
    Decreg4 := io.din4
    io.dout4 := Decreg4
    Decreg5 := io.din5
    io.dout5 := Decreg5
    Decreg6 := io.din6
    io.dout6 := Decreg6
    Decreg7 := io.din7
    io.dout7 := Decreg7
    Decreg8 := io.din8
    io.dout8 := Decreg8
    Decreg9 := io.din9
    io.dout9 := Decreg9
    Decreg10 := io.din10
    io.dout10 := Decreg10
    Decreg11 := io.din11
    io.dout11 := Decreg11
    Decreg12 := io.din12
    io.dout12 := Decreg12
    Decreg13 := io.din13
    io.dout13 := Decreg13
    Decreg14 := io.din14
    io.dout14 := Decreg14
    Decreg15 := io.din15
    io.dout15 := Decreg15
    Decreg16 := io.din16
    io.dout16 := Decreg16
    Decreg17 := io.din17
    io.dout17 := Decreg17

}